import { writeFileSync } from 'node:fs'
import fg from 'fast-glob'
import { camelCase } from 'lodash-es'
import { generatorsFile, srcDir } from '../internal/paths'

const generators = fg.globSync('*-generator', {
  cwd: srcDir,
  deep: 1,
  onlyDirectories: true,
})

writeFileSync(
  generatorsFile,
  `\
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by scripts/gen-generators.ts
${generators
  .map(
    (name) =>
      `export * from './${name}'\nexport { default as ${camelCase(
        `setup-${name}`,
      )} } from './${name}'`,
  )
  .join('\n')}
`,
)
